- type: job
  id: Captain
  name: job-name-captain
  description: job-description-captain
  playTimeTracker: JobCaptain
  requirements:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 0 # 0 hours
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 0 # 0 hours
    - !type:DepartmentTimeRequirement
      department: Security
      time: 0 # 0 hours
    - !type:DepartmentTimeRequirement
      department: Command
      time: 10800 # 3 hours
  weight: 20
  startingGear: CaptainGear
  icon: "JobIconCaptain"
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

# Harmony Change: Captain now spawns with a sabre. This will be used later for loadouts involving different swords.
- type: startingGear
  id: CaptainGear
  equipment:
    shoes: ClothingShoesBootsLaceup
    eyes: ClothingEyesGlassesSunglasses
    belt: ClothingBeltSheathFilled
    gloves: ClothingHandsGlovesCaptain
    id: CaptainPDA
    ears: ClothingHeadsetAltCommand
  storage:
    back:
    - Flash
    # - StationCharter
